// <auto-generated />
namespace DevFormAz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class changed_virtual_user_to_list_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed_virtual_user_to_list_user));
        
        string IMigrationMetadata.Id
        {
            get { return "202001041227249_changed_virtual_user_to_list_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
