// <auto-generated />
namespace DevFormAz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class change_form_userid_to_userdetailid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_form_userid_to_userdetailid));
        
        string IMigrationMetadata.Id
        {
            get { return "202001071343246_change_form_userid_to_userdetailid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
