// <auto-generated />
namespace DevFormAz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class deleted_mothly_dailyusecount_from_taglist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleted_mothly_dailyusecount_from_taglist));
        
        string IMigrationMetadata.Id
        {
            get { return "202001121339362_deleted_mothly_dailyusecount_from_taglist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
