// <auto-generated />
namespace DevFormAz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class updated_form_taglist_added_virtual : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_form_taglist_added_virtual));
        
        string IMigrationMetadata.Id
        {
            get { return "202001071338147_updated_form_taglist_added_virtual"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
