// <auto-generated />
namespace DevFormAz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class added_isactive_to_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_isactive_to_user));
        
        string IMigrationMetadata.Id
        {
            get { return "202001021202199_added_isactive_to_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
