// <auto-generated />
namespace DevFormAz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Added_User_UserControl_Prop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_User_UserControl_Prop));
        
        string IMigrationMetadata.Id
        {
            get { return "202001011308479_Added_User_UserControl_Prop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
