// <auto-generated />
namespace DevFormAz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class deleted_virtual_subs_from_userdetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleted_virtual_subs_from_userdetail));
        
        string IMigrationMetadata.Id
        {
            get { return "202001171224008_deleted_virtual_subs_from_userdetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
