// <auto-generated />
namespace DevFormAz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class updated_userdetail_table_skills_list_to_array : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_userdetail_table_skills_list_to_array));
        
        string IMigrationMetadata.Id
        {
            get { return "202001041201148_updated_userdetail_table_skills_list_to_array"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
