// <auto-generated />
namespace DevFormAz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class deleted_likeUnlike_from_added_like_from_formlike : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleted_likeUnlike_from_added_like_from_formlike));
        
        string IMigrationMetadata.Id
        {
            get { return "202001081016111_deleted_likeUnlike_from_added_like_from_formlike"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
