// <auto-generated />
namespace DevFormAz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class add_virtual_userdetail_from_job : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_virtual_userdetail_from_job));
        
        string IMigrationMetadata.Id
        {
            get { return "202001171227052_add_virtual_userdetail_from_job"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
